services:
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backend
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   ports:
  #     - "3000:3000"
  #     - "5555:5555"
  #   env_file:
  #     - .env
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   restart: always
  #   networks:
  #     - sakila
  
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./db:/docker-entrypoint-initdb.d
#     networks:
#       - sakila

# networks:
#   sakila: